### ISSUE TITLE
NRE in Sugar.HttpResponse..ctor

### ISSUE THREAD

**Issue by evgeny-k** [remobjects/sugar#26]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sugar.HttpResponse..ctor(HttpWebResponse aResponse)
   at Sugar.Http.ExecuteRequestSynchronous(HttpRequest aRequest)
   at Sugar.Http.GetXml(HttpRequest aRequest)
   at RemObjects.SDK.CodeGen4.RodlLibrary.LoadFromUrl(String aUrl) in ..\RodlReader.pas:line 690
   at RemObjects.SDK.CodeGen4.RodlLibrary..ctor(String aFilename) in ..\RodlReader.pas:line 585
   at RemObjects.CodeGen4.__Global.main(String[] __args) in ..\Program.swift:line 112
```
steps: 
- launch handmade rodl2code.exe as
```
rodl2code.exe  http://localhost:8099/bin --type:intf --platform:delphi --language:delphi
```

**Comment by evgeny-k** [comment]
76494: Sugar: NRE in Sugar.HttpResponse..ctor
